package com.ammdev.ofbrsrvcreateconsent.application.domain.enums;

public enum PermissionsEnum {
    ACCOUNTS_READ(1L, "ACCOUNTS_READ"),
    ACCOUNTS_BALANCES_READ(2L, "ACCOUNTS_BALANCES_READ"),
    ACCOUNTS_TRANSACTIONS_READ(3L, "ACCOUNTS_TRANSACTIONS_READ"),
    ACCOUNTS_OVERDRAFT_LIMITS_READ(4L, "ACCOUNTS_OVERDRAFT_LIMITS_READ"),
    CREDIT_CARDS_ACCOUNTS_READ(5L, "CREDIT_CARDS_ACCOUNTS_READ"),
    CREDIT_CARDS_ACCOUNTS_BILLS_READ(6L, "CREDIT_CARDS_ACCOUNTS_BILLS_READ"),
    CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ(7L, "CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ"),
    CREDIT_CARDS_ACCOUNTS_LIMITS_READ(8L, "CREDIT_CARDS_ACCOUNTS_LIMITS_READ"),
    CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ(9L, "CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ"),
    CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ(10L, "CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ"),
    CUSTOMERS_PERSONAL_ADITTIONALINFO_READ(11L, "CUSTOMERS_PERSONAL_ADITTIONALINFO_READ"),
    CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ(12L, "CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ"),
    CUSTOMERS_BUSINESS_ADITTIONALINFO_READ(13L, "CUSTOMERS_BUSINESS_ADITTIONALINFO_READ"),
    FINANCINGS_READ(14L, "FINANCINGS_READ"),
    FINANCINGS_SCHEDULED_INSTALMENTS_READ(15L, "FINANCINGS_SCHEDULED_INSTALMENTS_READ"),
    FINANCINGS_PAYMENTS_READ(16L, "FINANCINGS_PAYMENTS_READ"),
    FINANCINGS_WARRANTIES_READ(17L, "FINANCINGS_WARRANTIES_READ"),
    INVOICE_FINANCINGS_READ(18L, "INVOICE_FINANCINGS_READ"),
    INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ(19L, "INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ"),
    INVOICE_FINANCINGS_PAYMENTS_READ(20L, "INVOICE_FINANCINGS_PAYMENTS_READ"),
    INVOICE_FINANCINGS_WARRANTIES_READ(21L, "INVOICE_FINANCINGS_WARRANTIES_READ"),
    LOANS_READ(22L, "LOANS_READ"),
    LOANS_SCHEDULED_INSTALMENTS_READ(23L, "LOANS_SCHEDULED_INSTALMENTS_READ"),
    LOANS_PAYMENTS_READ(24L, "LOANS_PAYMENTS_READ"),
    LOANS_WARRANTIES_READ(25L, "LOANS_WARRANTIES_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_READ(26L, "UNARRANGED_ACCOUNTS_OVERDRAFT_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ(27L, "UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ(28L, "UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ(29L, "UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ"),
    RESOURCES_READ(30L, "RESOURCES_READ"),
    BANK_FIXED_INCOMES_READ(31L, "BANK_FIXED_INCOMES_READ"),
    CREDIT_FIXED_INCOMES_READ(32L, "CREDIT_FIXED_INCOMES_READ"),
    FUNDS_READ(33L, "FUNDS_READ"),
    VARIABLE_INCOMES_READ(34L, "VARIABLE_INCOMES_READ"),
    TREASURE_TITLES_READ(35L, "TREASURE_TITLES_READ"),
    EXCHANGES_READ(36L, "EXCHANGES_READ");

    private final Long id;
    private final String value;

    PermissionsEnum(Long id, String value) {
        this.id = id;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public String getValue() {
        return value;
    }
}