package com.ammdev.ofbrsrvcreateconsent.application.domain.enums;

public enum PermissionsEnum {
    ACCOUNTS_READ(1, "ACCOUNTS_READ"),
    ACCOUNTS_BALANCES_READ(2, "ACCOUNTS_BALANCES_READ"),
    ACCOUNTS_TRANSACTIONS_READ(3, "ACCOUNTS_TRANSACTIONS_READ"),
    ACCOUNTS_OVERDRAFT_LIMITS_READ(4, "ACCOUNTS_OVERDRAFT_LIMITS_READ"),
    CREDIT_CARDS_ACCOUNTS_READ(5, "CREDIT_CARDS_ACCOUNTS_READ"),
    CREDIT_CARDS_ACCOUNTS_BILLS_READ(6, "CREDIT_CARDS_ACCOUNTS_BILLS_READ"),
    CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ(7, "CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ"),
    CREDIT_CARDS_ACCOUNTS_LIMITS_READ(8, "CREDIT_CARDS_ACCOUNTS_LIMITS_READ"),
    CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ(9, "CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ"),
    CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ(10, "CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ"),
    CUSTOMERS_PERSONAL_ADITTIONALINFO_READ(11, "CUSTOMERS_PERSONAL_ADITTIONALINFO_READ"),
    CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ(12, "CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ"),
    CUSTOMERS_BUSINESS_ADITTIONALINFO_READ(13, "CUSTOMERS_BUSINESS_ADITTIONALINFO_READ"),
    FINANCINGS_READ(14, "FINANCINGS_READ"),
    FINANCINGS_SCHEDULED_INSTALMENTS_READ(15, "FINANCINGS_SCHEDULED_INSTALMENTS_READ"),
    FINANCINGS_PAYMENTS_READ(16, "FINANCINGS_PAYMENTS_READ"),
    FINANCINGS_WARRANTIES_READ(17, "FINANCINGS_WARRANTIES_READ"),
    INVOICE_FINANCINGS_READ(18, "INVOICE_FINANCINGS_READ"),
    INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ(19, "INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ"),
    INVOICE_FINANCINGS_PAYMENTS_READ(20, "INVOICE_FINANCINGS_PAYMENTS_READ"),
    INVOICE_FINANCINGS_WARRANTIES_READ(21, "INVOICE_FINANCINGS_WARRANTIES_READ"),
    LOANS_READ(22, "LOANS_READ"),
    LOANS_SCHEDULED_INSTALMENTS_READ(23, "LOANS_SCHEDULED_INSTALMENTS_READ"),
    LOANS_PAYMENTS_READ(24, "LOANS_PAYMENTS_READ"),
    LOANS_WARRANTIES_READ(25, "LOANS_WARRANTIES_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_READ(26, "UNARRANGED_ACCOUNTS_OVERDRAFT_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ(27, "UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ(28, "UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ(29, "UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ"),
    RESOURCES_READ(30, "RESOURCES_READ"),
    BANK_FIXED_INCOMES_READ(31, "BANK_FIXED_INCOMES_READ"),
    CREDIT_FIXED_INCOMES_READ(32, "CREDIT_FIXED_INCOMES_READ"),
    FUNDS_READ(33, "FUNDS_READ"),
    VARIABLE_INCOMES_READ(34, "VARIABLE_INCOMES_READ"),
    TREASURE_TITLES_READ(35, "TREASURE_TITLES_READ"),
    EXCHANGES_READ(36, "EXCHANGES_READ");

    private final Long id;
    private final String value;

    PermissionsEnum(Long id, String value) {
        this.id = id;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public String getValue() {
        return value;
    }
}